<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ETS2ReverseEnvironment</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TsMap">
      <HintPath>bin\TsMap.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>
